### ISSUE TITLE
the server has asked for the client to provide credentials

### ISSUE THREAD

**Issue by renatovieiraarmac** [koslib/helm-eks-action#47]
I'm using the plugin to deploy to my cluster and I'm getting this error below:

`Error: Kubernetes cluster unreachable: the server has asked for the client to provide credentials`

The kuibe config file is configured as secret in the github action.

My config:

```
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1

    - name: Set Kube Config
      run: |
        aws eks update-kubeconfig --name k8s --region sa-east-1
        echo 'KUBE_CONFIG_DATA<<EOF' >> $GITHUB_ENV
        ec ~/.kube/config | base64) >> $GITHUB_ENV
        echo $(cat ~/.kube/config)
        echo 'EOF' >> $GITHUB_ENV

    - name: helm deploy
      uses: koslib/helm-eks-action@v1.25.2
      env:
        KUBE_CONFIG_DATA: ${{ env.KUBE_CONFIG_DATA }}
        ENV: ${{ steps.extract_branch.outputs.branch }}
        IMAGE_TAG: ${{ github.sha }}
      with:
        command: helm upgrade api --install --wait k8s --namespace $ENV --set=env=$ENV,image_tag=$IMAGE_TAG
```

**Comment by koslib** [comment]
Hello @renatovieiraarmac please prompt me if I am wrong but it seems there is a typo here?

```
 ec ~/.kube/config | base64) >> $GITHUB_ENV
```

`ec` vs `echo`

Am I missing something?

**Comment by miparnisari** [comment]
Getting the same error:

```yaml
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          role-session-name: github-action-load-test-${{ github.run_id }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: helm setup
        uses: koslib/helm-eks-action@master
        with:
          command: |
            aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.CLUSTER }} --role-arn ${{ secrets.AWS_IAM_ROLE }} --kubeconfig ./kubeconfig
            echo 'KUBE_CONFIG_DATA<<EOF' >> $GITHUB_ENV
            echo $(cat ./kubeconfig | base64) >> $GITHUB_ENV
            echo 'EOF' >> $GITHUB_ENV
            kubectl config set-context arn:aws:eks:${{ secrets.AWS_REGION }}:${{ secrets.AWS_ACCOUNT }}:cluster/${{ secrets.CLUSTER }}

      - name: helm deploy
        uses: koslib/helm-eks-action@master
        env:
          KUBE_CONFIG_DATA: ${{ env.KUBE_CONFIG_DATA }}
        with:
          command: |
            helm repo add openfga https://openfga.github.io/helm-charts
            helm repo update
            helm install ${{ steps.vars.outputs.sha_short }} openfga/openfga --debug \
```

error

```shell
running entrypoint command(s)
install.go:192: [debug] Original chart version: ""
install.go:209: [debug] CHART PATH: /github/home/.cache/helm/repository/openfga-0.1.8.tgz

Error: INSTALLATION FAILED: Kubernetes cluster unreachable: the server has asked for the client to provide credentials
helm.go:84: [debug] the server has asked for the client to provide credentials
Kubernetes cluster unreachable
helm.sh/helm/v3/pkg/kube.(*Client).IsReachable
	helm.sh/helm/v3/pkg/kube/client.go:121
```

**Comment by renatovieiraarmac** [comment]
Working after update plugin koslib/helm-eks-action@master to version before

**Comment by miparnisari** [comment]
@renatovieiraarmac can you be more specific? What version are you using now?

**Comment by renatovieiraarmac** [comment]
> 

Sure. 

This version: koslib/helm-eks-action@v1.25.2

**Comment by renatovieiraarmac** [comment]
> @renatovieiraarmac can you be more specific? What version are you using now?

Recommended use fluxcd.io to ci/cd based in image from ECR

**Comment by miparnisari** [comment]
@koslib thanks for the comment, now I get this:

> An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::***:assumed-role/github-action-load-test/GitHubActions is not authorized to perform: sts:AssumeRole on resource: ***
Error: INSTALLATION FAILED: Kubernetes cluster unreachable: Get "[https://43769B9B37F5703BB25FC3C0822C466A.gr7.***.eks.amazonaws.com/version](https://43769b9b37f5703bb25fc3c0822c466a.gr7.%2A%2A%2A.eks.amazonaws.com/version)": getting credentials: exec: executable aws failed with exit code 255

_now_ i'm sure my IAM role is set up incorrectly 😓

**Comment by miparnisari** [comment]
@koslib thanks for the comment, now I get this:

> An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::***:assumed-role/github-action-load-test/GitHubActions is not authorized to perform: sts:AssumeRole on resource: ***
Error: INSTALLATION FAILED: Kubernetes cluster unreachable: Get "[https://xxxx.gr7.***.eks.amazonaws.com/version](https://xxxx.gr7.%2A%2A%2A.eks.amazonaws.com/version)": getting credentials: exec: executable aws failed with exit code 255

_now_ i'm sure my IAM role is set up incorrectly 😓  it currently has

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "eks:*"
            ],
            "Resource": "*"
        }, {
            "Effect": "Allow",
            "Action": "ecr:GetAuthorizationToken",
            "Resource": "*"
        }
    ]
}
```

**Comment by renatovieiraarmac** [comment]
> @koslib thanks for the comment, now I get this:
> 
> > An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::***:assumed-role/github-action-load-test/GitHubActions is not authorized to perform: sts:AssumeRole on resource: ***
> > Error: INSTALLATION FAILED: Kubernetes cluster unreachable: Get "[https://xxxx.gr7.***.eks.amazonaws.com/version](https://xxxx.gr7.%2A%2A%2A.eks.amazonaws.com/version)": getting credentials: exec: executable aws failed with exit code 255
> 
> _now_ i'm sure my IAM role is set up incorrectly 😓 it currently has
> 
> ```json
> {
>     "Version": "2012-10-17",
>     "Statement": [
>         {
>             "Effect": "Allow",
>             "Action": [
>                 "eks:*"
>             ],
>             "Resource": "*"
>         }, {
>             "Effect": "Allow",
>             "Action": "ecr:GetAuthorizationToken",
>             "Resource": "*"
>         }
>     ]
> }
> ```

try test more permission to ECR, try ecr: * 
not recommended, but, working to test

**Comment by miparnisari** [comment]
Nope, didn't work :(

**Comment by renatovieiraarmac** [comment]
> Nope, didn't work :(

This case not problem in policy. This account need assume role with permission to assume ecr

**Comment by miparnisari** [comment]
The role permissions were right. The problem was that `aws-actions/configure-aws-credentials@v2` uses a session tag. 

```
      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
```

So, the trust policy in the role has to have

```
{
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:sts::<Account>:assumed-role/<Role>/GitHubActions"
            },
            "Action": "sts:AssumeRole"
        }
```

Also, I needed to manually run this (i guess the github action can do it as well)

```
eksctl create iamidentitymapping \
    --cluster ${{ secrets.CLUSTER }} \
    --region ${{ secrets.AWS_REGION }} \
    --arn ${{ secrets.AWS_IAM_ROLE }} \
    --group system:masters \
    --no-duplicate-arns \
    --username github-action
