### ISSUE TITLE
Kubernetes cluster unreachable: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"

### ISSUE THREAD

**Issue by kalinowski5** [koslib/helm-eks-action#62]
Hi!

I'm getting the following error:
```Kubernetes cluster unreachable: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"```

for the following action:
```
      - name: Deploy to test cluster
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: koslib/helm-eks-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_TEST }}
        with:
          command: helm upgrade --atomic --install --values "operations/kubernetes/acme-service/configuration/test/environment-values.yaml" --namespace "acme-service-test" --set "nutrition.version=$REVISION_TAG" --wait --timeout 600s acme-service-test ./operations/kubernetes/acme-service
``` 

Is there anything that I could change/improve?

I tried to pin version of koslib/helm-eks-action to `v1.25.2` and `v1.22.0`, but this didn't help.
